"""
Constants used by the base module and imported throughout the codebase.
"""

# Size and scale constants
DEFAULT_WORKPLANE_SIZE = 0.4
DEFAULT_ENTITY_SCALE = 1.0
DEFAULT_GIZMO_SCALE = 15.0
DEFAULT_TEXT_SIZE = 15
DEFAULT_ARROW_SCALE = 1.0

# Precision constants
DEFAULT_DECIMAL_PRECISION = 3
DEFAULT_ANGLE_PRECISION = 0

# Boolean preference defaults
DEFAULT_SHOW_DEBUG_SETTINGS = False
DEFAULT_HIDE_INACTIVE_CONSTRAINTS = True
DEFAULT_ALL_ENTITIES_SELECTABLE = False
DEFAULT_FORCE_REDRAW = True
DEFAULT_AUTO_HIDE_OBJECTS = True
DEFAULT_USE_ALIGN_VIEW = True
DEFAULT_SHOW_THEME_SETTINGS = False